spring:
  profiles:
    # '@profileActive@'表示该属性值会在maven构建时被替换掉。
    active: '@profileActive@'

  mvc:
    view:
      prefix: /pages/
      suffix: .html
  thymeleaf:
    encoding: utf-8
    mode: HTML5
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
server:
  port: 8080

# MyBatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  path: /var/tmp/zsblog